version: "3.5"

services:
  node:
    container_name: wtp_node
    build:
      context: ./wtp-client
    command: 'npm run start'
    ports:
      - "4200:4200"
    volumes:
      - ./wtp-client:/root
    networks:
      - wtp_net
networks:
  wtp_net:
    name: wtp_net
