version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16
executors:
  wtp-client-docker:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.0-browsers
jobs:
  checkout:
    executor: wtp-client-docker
    steps:
      - attach_workspace:
          at: .
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  install:
    executor: wtp-client-docker
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "install"
          command: "npm i"
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor: wtp-client-docker
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "test"
          command: "npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI"
  e2e:
    executor: wtp-client-docker
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "e2e"
          command: "npm run e2e"
  build:
    executor: wtp-client-docker
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "set env variables"
          command: "./scripts/set-vars.sh"
      - run:
          name: "build"
          command: "npm run build -- ${NG_BUILD_ARGS}"
  deploy-to-s3:
    executor: wtp-client-docker
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "set env variables"
          command: "./scripts/set-vars.sh"
      - run:
          name: "copy to S3"
          command: "aws s3 sync dist/wtp-client ${S3_DEST} --delete --acl public-read --cache-control max-age=86400"
workflows:
  version: 2.0
  build-and-deploy:
    jobs:
      - checkout
      - install:
          requires:
            - checkout
      - test:
          requires:
            - install
      - e2e:
          requires:
            - install
      - build:
          requires:
            - test
            - e2e
