version: 2.1
orbs:
  aws-s3: circleci/aws-ecr@0.0.2
workflows:
  test:
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
  # build-deploy:
  #   steps:
  #     - checkout
  #         steps:
  #           - run: npm install
  #     - run: npm run test
