version: 2.1
orbs:
  aws-s3: circleci/aws-ecr@0.0.2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.0-browsers
    steps:
      - checkout
      - run:
          name: 'install'
          command: 'npm i'
      - run:
          name: 'test'
          command: 'npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI'
      - run:
          name: 'e2e'
          command: 'npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js'
      - run:
          name: 'build'
          command: 'npm run build'
      - aws-s3/copy:
          from: dist
          to: 's3://wtp-web-develop'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

  # build-deploy:
  #   steps:
  #     - checkout
  #         steps:
  #           - run: npm install
  #     - run: npm run test
