version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16
executors:
  wtp-client-docker:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.0-browsers
jobs:
  set-env-vars:
    executor: wtp-client-docker
    steps:
      - run:
          name: 'set environment vars'
          command: './scripts/set-vars.sh'
  checkout:
    executor: wtp-client-docker
    steps:
      - checkout
  install:
    executor: wtp-client-docker
    steps:
      - run:
        name: 'install'
        command: 'npm i'
  build:
    executor: wtp-client-docker
    steps:
      - run:
        name: 'build'
        command: 'npm run build'
  test:
    executor: wtp-client-docker
    steps:
        - run:
          name: 'test'
          command: 'npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI'
  e2e:
    executor: wtp-client-docker
    steps:
      - run:
          name: 'build'
          command: 'npm run e2e'
  deploy-to-s3:
    executor: wtp-client-docker
    steps:
      - run:
          name: 'copy to S3'
          command: 'aws s3 sync dist/wtp-client ${S3_DEST} --delete --acl public-read --cache-control max-age=86400'
workflows:
    version: 2.0
    setup:
      jobs:
        - checkout
        - set-env-vars
        - install
    test:
      requires:
        - setup
      jobs:
        - test
        - e2e
    build:
      requires:
        - test
      jobs:
        - build
    deploy:
      requires:
        - build
      jobs:
        - aws-cli/install
        - aws-cli/configure
        - deploy-to-s3


