version: 2.1
orbs:
  aws-s3: circleci/aws-ecr@0.0.2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run_test:
          name: 'test'
          command: 'npm run test'
      - run_build:
          name: 'build'
          command: 'npm run build'
      # - aws-s3/copy:
      #     name: 'deploy'
      #     command: 'echo "hello"'

  # build-deploy:
  #   steps:
  #     - checkout
  #         steps:
  #           - run: npm install
  #     - run: npm run test
