version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.0-browsers
    steps:
      - checkout
      - run:
          name: 'set environment vars'
          command: './scripts/set-vars.sh'
      - aws-cli/install
      - aws-cli/configure
      - run:
          name: 'install'
          command: 'npm i'
      - run:
          name: 'test'
          command: 'npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI'
      - run:
          name: 'e2e'
          command: 'npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js'
      - run:
          name: 'build'
          command: 'npm run build -- ${NG_BUILD_ARGS}'
      - run:
          name: 'ls'
          command: 'ls dist'
      - run:
          name: 'copy to S3'
          command: 'aws s3 sync dist/wtp-client ${S3_DEST} --delete --acl public-read --cache-control max-age=86400'
